### ISSUE TITLE
Stop shipping GLFW with Horde3D SDK

### ISSUE THREAD

**Issue by siavashserver** [attilaz/horde3d-x#3]
Shipping GLFW with Horde3D SDK makes compiling and running samples easier by newbies, but I don't think it is a good idea to ship an old version of GLFW 2.7 missing a lot of bug fixes or going in trouble of updating bundled GLFW with every release with GLFW 3 being on the edge.

So my suggestion is to remove bundled GLFW from Horde3D SDK or atleast from the git repository and dynamically link against the installed version on target system.

**Comment by bagobor** [comment]
GIT modules ? :)

**Comment by siavashserver** [comment]
Thanks for pointing that out, it's really a nice feature that I wasn't aware of. GLFW 2.x series are pretty much stable and upstream is very reliable, however I still think it's better to keep using and linking to official packages provided by Linux distributions for our development github repository, so we don't need to puzzle with non-Horde3D issues.

**Comment by tyoc213** [comment]
I just send a pull request to upstream https://github.com/horde3d/Horde3D/pull/13 for this

By the way @attilaz (I haven't compared) but how much different is this repo from the forked one? (https://github.com/attilaz/Horde3D) will you do a long-term branch? or it is different?

**Comment by attilaz** [comment]
my work is in the gles_d3d11 branch. It is still not finished. I haven't done any changes in attilaz/Horde
