### ISSUE TITLE
Fork from official Horde3d repository

### ISSUE THREAD

**Issue by ghost** [attilaz/horde3d-x#5]
There is an official Horde3d repository. Will Horde3d-x and its branches become a fork of the official repository?

**Comment by attilaz** [comment]
Yes. Unfortunately h3d-x was created before the official github repo. I will fork and merge my branch (gles2_d3d11).
Probably will erase h3d-x after that...

**Comment by ghost** [comment]
I want to merge some changes that will allow the gles2 branch to work on embedded devices as well. When do you plan to fork and merge?

**Comment by attilaz** [comment]
Don't have too much time right now. Probably in the end of next month.

**Comment by tyoc213** [comment]
http://stackoverflow.com/a/14992078/682603 that could be the way now included in git itself so the official repo was marked as obsolete :) https://github.com/apenwarr/git-subtree/blob/master/THIS-REPO-IS-OBSOLETE 

And sure the guide http://git-scm.com/book/en/Git-Tools-Subtree-Merging

technically that means that "any of us" can try to get the steps correct ;)... easing the testing on how to do it correctly and report "back" & paste the lines.
